'use strict';

const _PATTERNS_HEAD = [
    { re: /\{#[\s\S]*?#\}/g, key: 'comment' },
    { re: /\{%-?[\s\S]*?-?%\}/g, key: 'jinja' },
    { re: /\{\{[\s\S]*?\}\}/g, key: 'jinja' },
    { re: /--[^\n]*/g, key: 'comment' },
    { re: /(?<=->>?[ \t]*)('[^']*'|"[^"]*")/g, key: 'json_path' },
    { re: /'[^']*'/g, key: 'string' },
    { re: /"[^"]*"/g, key: 'string' },
    { re: /`[^`]+`/g, key: 'identifier' },
    { re: /:[a-zA-Z_][a-zA-Z0-9_]*/g, key: 'param' },
    { re: /\b(TRUE|FALSE|NULL)\b/gi, key: 'boolean' },
];

const _PATTERNS_TAIL = [
    { re: /\b\d+(\.\d+)?\b/g, key: 'number' },
    { re: /->>|->|!=|<>|<=|>=|[<>=]/g, key: 'operator' },
];

const SPECIFIC_PATTERNS_SQL = [
    ..._PATTERNS_HEAD,
    {
        re: /\b(SELECT|FROM|WHERE|AND|OR|NOT|IN|LIKE|ILIKE|BETWEEN|IS|JOIN|LEFT|RIGHT|INNER|OUTER|CROSS|FULL|NATURAL|ON|USING|WITH|AS|DISTINCT|ORDER|BY|GROUP|HAVING|LIMIT|OFFSET|UNION|INTERSECT|EXCEPT|ALL|INSERT|INTO|VALUES|UPDATE|SET|DELETE|CREATE|ALTER|DROP|TABLE|VIEW|INDEX|EXISTS|CASE|WHEN|THEN|ELSE|END|RETURNING|PARTITION|OVER|WINDOW|ASC|DESC|NULLS|FIRST|LAST|INTERVAL|MICROSECOND|SECOND|MINUTE|HOUR|DAY|WEEK|MONTH|QUARTER|YEAR|SECOND_MICROSECOND|MINUTE_MICROSECOND|MINUTE_SECOND|HOUR_MICROSECOND|HOUR_SECOND|HOUR_MINUTE|DAY_MICROSECOND|DAY_SECOND|DAY_MINUTE|DAY_HOUR|YEAR_MONTH|JSON|LATERAL|RECURSIVE|MATCH|AGAINST|REGEXP|RLIKE|EXPLAIN|ANALYZE|TRUNCATE|REPLACE|ROLLUP|CUBE|GROUPING|SEPARATOR|MERGE|MATCHED|ESCAPE|COLLATE|BINARY|STRAIGHT_JOIN|WITHIN|DUPLICATE|KEY)\b/gi,
        key: 'keyword',
    },
    {
        re: /\b(COUNT|SUM|AVG|MIN|MAX|COALESCE|NULLIF|IFNULL|IF|ROW|CONCAT|CONCAT_WS|SUBSTRING|SUBSTR|LENGTH|TRIM|LTRIM|RTRIM|UPPER|LOWER|REPLACE|INSTR|DATE|DATE_FORMAT|TIME_FORMAT|DATE_ADD|DATE_SUB|DATEDIFF|NOW|CURDATE|CAST|CONVERT|GROUP_CONCAT|ROW_NUMBER|RANK|DENSE_RANK|LEAD|LAG|FIRST_VALUE|LAST_VALUE|ROUND|FLOOR|CEIL|CEILING|ABS|MOD|POWER|GREATEST|LEAST|TIMESTAMPDIFF|EXTRACT|JSON_EXTRACT|JSON_UNQUOTE|GROUPING|JSON_ARRAYAGG|JSON_OBJECTAGG|POSITION|LOCATE|FIND_IN_SET|FIELD|UUID|DATABASE|SCHEMA)\s*(?=\()/gi,
        key: 'function',
    },
    ..._PATTERNS_TAIL,
];

const SPECIFIC_PATTERNS_BQ = [
    ..._PATTERNS_HEAD,
    {
        re: /\b(SELECT|FROM|WHERE|AND|OR|NOT|IN|LIKE|ILIKE|BETWEEN|IS|JOIN|LEFT|RIGHT|INNER|OUTER|CROSS|FULL|NATURAL|ON|USING|WITH|AS|DISTINCT|ORDER|BY|GROUP|HAVING|LIMIT|OFFSET|UNION|INTERSECT|EXCEPT|ALL|INSERT|INTO|VALUES|UPDATE|SET|DELETE|CREATE|ALTER|DROP|TABLE|VIEW|INDEX|EXISTS|CASE|WHEN|THEN|ELSE|END|RETURNING|PARTITION|OVER|WINDOW|ASC|DESC|NULLS|FIRST|LAST|INTERVAL|MICROSECOND|SECOND|MINUTE|HOUR|DAY|WEEK|MONTH|QUARTER|YEAR|SECOND_MICROSECOND|MINUTE_MICROSECOND|MINUTE_SECOND|HOUR_MICROSECOND|HOUR_SECOND|HOUR_MINUTE|DAY_MICROSECOND|DAY_SECOND|DAY_MINUTE|DAY_HOUR|YEAR_MONTH|JSON|QUALIFY|TABLESAMPLE|PIVOT|UNPIVOT|STRUCT|ARRAY|UNNEST|TIMESTAMP|DATETIME|TIME|FOLLOWING|PRECEDING|UNBOUNDED|ROWS|RANGE|IGNORE|RESPECT|LATERAL|RECURSIVE|MATCH|AGAINST|REGEXP|RLIKE|EXPLAIN|ANALYZE|TRUNCATE|REPLACE|ROLLUP|CUBE|GROUPING|SEPARATOR|MERGE|MATCHED|ESCAPE|COLLATE|BINARY|STRAIGHT_JOIN|WITHIN|DUPLICATE|KEY)\b/gi,
        key: 'keyword',
    },
    {
        re: /\b(COUNT|SUM|AVG|MIN|MAX|COALESCE|NULLIF|IFNULL|IF|CONCAT|CONCAT_WS|SUBSTRING|SUBSTR|LENGTH|TRIM|LTRIM|RTRIM|UPPER|LOWER|REPLACE|INSTR|DATE|DATE_FORMAT|TIME_FORMAT|DATE_ADD|DATE_SUB|DATEDIFF|NOW|CURDATE|CAST|CONVERT|GROUP_CONCAT|ROW_NUMBER|RANK|DENSE_RANK|LEAD|LAG|FIRST_VALUE|LAST_VALUE|ROUND|FLOOR|CEIL|CEILING|ABS|MOD|POWER|GREATEST|LEAST|TIMESTAMPDIFF|EXTRACT|JSON_EXTRACT|JSON_UNQUOTE|GROUPING|JSON_ARRAYAGG|JSON_OBJECTAGG|POSITION|LOCATE|FIND_IN_SET|FIELD|UUID|DATABASE|SCHEMA|STRING_AGG|ARRAY_AGG|ARRAY_LENGTH|ARRAY_TO_STRING|ARRAY_CONCAT|ARRAY_REVERSE|GENERATE_ARRAY|ANY_VALUE|COUNTIF|LOGICAL_AND|LOGICAL_OR|APPROX_COUNT_DISTINCT|PERCENTILE_CONT|PERCENTILE_DISC|PERCENT_RANK|CUME_DIST|NTILE|NTH_VALUE|REGEXP_REPLACE|REGEXP_EXTRACT|REGEXP_CONTAINS|DATE_TRUNC|TIMESTAMP_TRUNC|DATETIME_TRUNC|DATETIME_ADD|DATETIME_SUB|DATETIME_DIFF|TIMESTAMP_ADD|TIMESTAMP_SUB|TIMESTAMP_DIFF|DATE_DIFF|PARSE_DATE|PARSE_TIMESTAMP|PARSE_DATETIME|FORMAT_DATE|FORMAT_TIMESTAMP|FORMAT_DATETIME|CURRENT_TIMESTAMP|CURRENT_DATE|CURRENT_TIME|CURRENT_DATETIME|SAFE_DIVIDE|SAFE_CAST|GENERATE_UUID|SPLIT|STARTS_WITH|ENDS_WITH|STRPOS|LPAD|RPAD|REPEAT|REVERSE|CHAR_LENGTH|BYTE_LENGTH|FORMAT|TO_BASE64|FROM_BASE64|TO_HEX|FROM_HEX|SHA256|MD5|FARM_FINGERPRINT|JSON_VALUE|JSON_QUERY|JSON_EXTRACT_SCALAR|JSON_EXTRACT_ARRAY|JSON_OBJECT|JSON_ARRAY|BIT_AND|BIT_OR|BIT_XOR|BIT_COUNT|RANGE_BUCKET|STRUCT|UNNEST|ARRAY)\s*(?=\()/gi,
        key: 'function',
    },
    ..._PATTERNS_TAIL,
];

const IDENT_RE = /\b[a-zA-Z_][a-zA-Z0-9_]*\b/g;
const CAPS_WORD_RE = /\b[A-Z][A-Z0-9_]{2,}\b/g;

module.exports = {
    CAPS_WORD_RE,
    IDENT_RE,
    SPECIFIC_PATTERNS_BQ,
    SPECIFIC_PATTERNS_SQL,
};
